### PR TITLE
Return same type as state

### PR DESCRIPTION
**Pull request by levino**
The reducer should return the state, not anything.

### CODE REVIEW

**Comment by monotv** [comment]
Awesome change.

**Comment by levino** [comment]
Looks like this project has been abandoned. Same functionality is provided by [`typed-actions`](https://github.com/lttb/typed-actions) which has better types and is more powerful. Closing.

**Comment by kolodny** [comment]
Whoops, sorry about that. It's not abandoned it's just that I sometimes miss the notifications or don't have time to take a look at PRs. I'm still open to this PR if you want to reopen

**Comment by levino** [comment]
Sure, my pleasure. I just wanted to clean up my open PRs. Thank you for looking into it.

**Comment by kolodny** [comment]
Looks like CI is failing. I need to bump the nodejs version, I'll spend some time (hopefully) tonight on that. Thanks for the PR!

**Comment by kolodny** [comment]
Merged and published to v.2.0.1. Thanks again

**Pull request merged**
