### PR TITLE
Fixed createReducer return type, and added OTHER_ACTION handling.

### PR DESCRIPTION
**Pull request by Shakeskeyboarde**
+ Fixed: `createReducer` creates a reducer which returns `any`, but should return `S` (state type).
+ Fixed: `Handlers` should be partial (allow missing actions types).
  + Reasoning: The target functionality should be equivalent to the vanilla `switch` implementation, which does not enforce handling all actions. Also, defining partial reducers is a common design pattern.
+ Fixed: Shouldn't use `.hasOwnProperty()` directly on a "map" object, because `hasOwnProperty` itself could be used as a key.
+ Renamed: `Reducer` -> `Handler` to disambiguate it from Redux's `Reducer` (which allows the input state to be `undefined`, unlike `Handler`).
+ Added: Exports for `Handler` and `Handlers`.
+ Added: `OTHER_ACTION` symbol which allows for a default handler.
+ Added: Test for `OTHER_ACTION`.

### CODE REVIEW

**Comment by kolodny** [comment]
Hmm, I'm not sure I agree with the idea behind `OTHER_ACTION`. This doesn't feel very redux'y since reducers will be called with potentially thousands of actions that should silently just return state. Reducers are more of an opt in mechanism. I'd consider it a huge code smell if someone is doing anything other than `return state` in the default block of a reducer. This library already returns state when no patterns match so I don't see much utility in that. I'm on board with the rest of the PR, including making handlers a partial. I was on the fence about doing that from the start and probably made a mistake with the direction I took

**Comment by Shakeskeyboarde** [comment]
While I agree it's probably not something to be used very often, it bothered me that it's not possible without completely discarding this utility. I don't have a scenario in mind, but being _able_ to detect this scenario just seemed reasonable, and potentially an extension point.

Also, _enforcing_ "good" behavior like that in code is also a little code-smelly, and maybe even non-reduxy. Redux doesn't actually enforce or proscribe any particular reducer behavior (like using or not using a switch statement). This utility provides for a pattern similar to a switch statement, but there are other things you could very reasonably do. For example, pre/post processors, logging, etc. The only scenario that can't be handled as it currently stands, is detecting that no handler was matched. Hence, a way to capture that edge case.

The intro here lays it out pretty nicely: https://redux.js.org/recipes/structuring-reducers/structuring-reducers. Paraphrased, "[Reducers] must be pure and predictable. Beyond that, Redux does not really care..."

**Comment by fxlrnrpt** [comment]
@ChrisAckerman I beg to differ that default handlers are not possible now, without that change.

```js
const myOriginalReducer = ...

const reducerWIthDefaultHandler = (state, action) => {
  const newState = myOriginalReducer(state, action)

  if (newState === state) {
    // default handler
    ...
   return state
  }
}

```

**Comment by Shakeskeyboarde** [comment]
I stand corrected @keenondrums 😊. Alright, then in that case, not only is it possible, I even think that’s better than an arbitrary symbol. I’ll update the PR.

**Comment by Shakeskeyboarde** [comment]
Although, sorry, now that I think more about it, that will tell you that nothing changed the state... not that it wasn’t handled. There is the case where the action type was matched by a handler, but the handler chose to return the same state. So I do think there’s still a reason to have it.

**Comment by kolodny** [comment]
I'm still not convinced `OTHER_ACTION` belongs in this library, it's a pretty slim use case for under %1 of all users of this library. Since this library is a well defined and scoped library, I'd suggest wrapping that functionality in a higher order module that could handle a case where no handler was called. Perhaps something along these lines:

```js
function wrapper(initialState, handlers) {
  const reducer = createReducer(initialState, handlers);
  return function(state, action) {
    if (handlers.hasOwnProperty(state.action)) {
      return reducer(state, action);
    }
    console.log('My custom handler');
    return state;
  }
}
```

**Comment by zaguiini** [comment]
While this PR isn't merged, you can type assert your reducer casting it with `as`.

Example:

```ts
createReducer(...) as React.Reducer<S, A>
```

**Comment by kolodny** [comment]
@zaguiini That sounds correct. It'd be nice to get the type improvements in. I'm still going to push back on the `OTHER_ACTION` change though...

**Comment by Shakeskeyboarde** [comment]
It seems like this isn't desired by the community :).

**Pull request closed without merging**
