### PR TITLE
Generic action types

### PR DESCRIPTION
**Pull request by JakeSidSmith**
This pull request adds both more flexible default types for actions, and the ability to supply more specific types while maintaining backwards compatibility.

I have added the ability to define a generic type for the handler actions, and a default value to match that of the redux types.

```typescript
A extends Action = AnyAction
```

I have used the existing `Action`, `AnyAction`, and `Reducer` types from redux, and added redux as a peer dependency.

By setting the default action as `AnyAction` consumers can easily specify more specific types for the action in their handlers.

E.g. if I have the custom type:

```typescript
interface MyAction extends Action {
  foo: 'bar';
}
```

Previously I could not have defined handlers with my more specific action type:

```typescript
createReducer({
  [actionType] (state: MyState, action: MyAction) { // Incompatible with current types
  }
})
```

This would give the following type error:

```
Type 'Action' is not assignable to type 'MyAction'.
Property 'foo' is missing in type 'Action'.
```

Using `AnyAction` allows more specific types in the handlers, and by adding a generic parameter for the action, consumers can also narrow the type themselves.

Now you can supply generic parameters to the `createReducer` function upon call:

```typescript
createReducer<MyState, MyAction>({});
```

And or when defining handlers:

```typescript
const handlers: Handlers<MyState, MyAction> = {};
```

### CODE REVIEW

**Comment by JakeSidSmith** [comment]
@kolodny any chance this could get merged?

**Comment by kolodny** [comment]
Hmm, I'm hesitant to make redux a peer dep. What happens if redux isn't available? I imagine this will pull in redux just for the type info. If you remove that line and the user doesn't have redux will this still work or will the type system be broken?

**Comment by JakeSidSmith** [comment]
When would you use a library for creating redux reducers without redux? 😕

**Comment by kolodny** [comment]
Fair enough

**Comment by JakeSidSmith** [comment]
Thank you. 😊

**Pull request merged**
